### ISSUE TITLE
Building `pp37-win32` wheel fails - Outdated `PyPy 3.7` download link

### ISSUE THREAD

**Issue by Saransh-cpp** [pypa/cibuildwheel#1041]
### Description

Reference workflow - https://downloads.python.org/pypy/pypy3.7-v7.3.3-win32.zip

Building `pp37-win32` wheel is failing on `Windows` `32bit` as `cibuildwheel` is trying to download `PyPy 3.7` through an outdated link (an older version) - https://downloads.python.org/pypy/pypy3.7-v7.3.3-win32.zip - which is no longer active. The active link is - https://downloads.python.org/pypy/pypy3.7-v7.3.8-win64.zip

Can this be fixed from our end or is this a core `cibuildwheel` issue?

### Build log

https://downloads.python.org/pypy/pypy3.7-v7.3.3-win32.zip

### CI config

https://github.com/Saransh-cpp/PyBaMM/blob/failing-build-wheels/.github/workflows/build_wheels.yml

**Comment by henryiii** [comment]
PyPy dropped Windows 32 bit support in version 7.3.4 (when they added 64-bit support, actually). Do you actually need 32-bit Windows PyPy wheels? Also, wasn't expecting the link to stop working, even it it's a bit older (and especially as the final supported version). CC @mattip.

**Comment by mattip** [comment]
- The link https://downloads.python.org/pypy/pypy3.7-v7.3.3-win32.zip is to a 32-bit version of PyPy which, as @henryiii points out is no longer supported.
- The link is still live, there was a temporary glitch in the hosting that prevented downloading it, so if you really desire you should be able to build 32-bit windows wheels (please do not though since they are unsupported)
- The link https://downloads.python.org/pypy/pypy3.7-v7.3.8-win64.zip is to a 64-bit version of the interpreter. This is what should be used going forward.

**Comment by Saransh-cpp** [comment]
Thank you for all the help, @henryiii and @mattip! Yes, the link is up again and the workflows are passing. We will definitely look into removing 32-bit windows wheels of `PyPy` in `PyBaMM`.
