### ISSUE TITLE
cibuildwheel fails to create virtual environment

### ISSUE THREAD

**Issue by Vadiml1024** [pypa/cibuildwheel#1239]
### Description

I'm getting:
/__t/Python/3.10.6/x64/bin/python: error while loading shared libraries: libpython3.10.so.1.0: cannot open shared object file: No such file or directory

When running cibuildwheel github action

### Build log

https://github.com/Vadiml1024/python-libarchive/runs/7935132697?check_suite_focus=true

### CI config

https://github.com/Vadiml1024/python-libarchive/blob/0f0abbfaeb5ab9f7f419652bb7724369e635ed35/.github/workflows/cibuildwheel.yml

**Comment by mayeut** [comment]
The CI config shows that you're trying to run the action inside a manylinux container:
https://github.com/Vadiml1024/python-libarchive/blob/0f0abbfaeb5ab9f7f419652bb7724369e635ed35/.github/workflows/cibuildwheel.yml#L27

This is not a valid setup for cibuildwheel (it would fail later on even if we got setup-python working in the container).

I guess you're running in a manylinux container in order to install/build your dependencies. You should be using the [CIBW_BEFORE_ALL](https://cibuildwheel.readthedocs.io/en/stable/options/#before-all) option to do so.

**Comment by mayeut** [comment]
Seems to be fixed the repo, closing issue.
