### ISSUE TITLE
Provide "major version" tag for the GitHub action

### ISSUE THREAD

**Issue by aaugustin** [pypa/cibuildwheel#1243]
### Description

If you look at the tags for an official GitHub action such as actions/checkout (https://github.com/actions/checkout/tags), you will see a `v3` tag that is updated to match the latest `v3.x.y` tag every time `v3.x.y` is released.

Adopting this practice for cibuildwheel would make it possible to configure GitHub workflow like this:

```yaml
      - name: Build wheels
        uses: pypa/cibuildwheel@v2
```

and get the latest v2.x.y automatically.

Of course it's possible to use the full version number and configure dependabot to update it; I did that. However, my project is released much less frequently than cibuildwheel. I find it annoying to merge 10 pull requests updating the cibuildwheel version without running cibuildwheel a single time. This doesn't feel useful. Just sticking with "the latest v2" would be good enough.

(I am familiar with the benefits of pinning to a specific version or even a specific SHA. Not every project wants this level of overhead.)

**Comment by henryiii** [comment]
Two problems: first, minor releases add new Python versions and new platform targets. So if you didn't support Python 3.11, secretly updating 2.8 -> 2.9 would cause your build to break. Since usually you don't build all your wheels except on releases, this would mean you'd only find out that your wheel build was broken after you released.

Second, the main purpose of the action is to allow dependabot to control your cibuildwheel version exactly. Cibuildwheel internally pins so that you have the highest possible chance of a build continuing to be build identically forever. You can have your wheel build action trigger on changes to the wheel workflow, so the update PRs get run fully, as well. If you just want to use the latest cibuildwheel, this is equivalent:

```yaml
- run: pipx run 'cibuildwheel==2.*'
```

And that allows you to control this in any way you'd like.

I'd recommend just turning down the dependabot frequency if you don't want PRs so often, something like monthly. Or you could even run dependabot manually just before releases.

**Comment by aaugustin** [comment]
That makes sense. Thank you for the advice.
