### ISSUE TITLE
musllinux ppc64le builds are affected by compiler / platform bug

### ISSUE THREAD

**Issue by tiran** [pypa/cibuildwheel#1250]
### Description

I was just made aware of the fact that cibuildwheel has build support for musllinux ppc64le. A while ago a user reported that Alpine Linux miscompiles CPython on ppc64le platforms and produces wrong code. CPython bug https://github.com/python/cpython/issues/92826 has more informations on the issue

Could you please verify that your images are not affected by the bug?

**Comment by tiran** [comment]
Update: I found cibuildwheels images for musllinux 1.1 ppc64le. The images are affected by the compiler bug and therefore broken. Any binary wheel created with this image should be considered broken.

```
$ podman run --platform linux/ppc64le -ti --rm quay.io/pypa/musllinux_1_1_ppc64le /opt/python/cp310-cp310/bin/python -c 'import struct; print(struct.Struct("!f").pack(1.0).hex())'
00000000
```

````
$ podman run --platform linux/ppc64le -ti --rm quay.io/pypa/manylinux_2_28_ppc64le /opt/python/cp310-cp310/bin/python -c 'import struct; print(struct.Struct("!f").pack(1.0).hex())'
3f800000
```

**Comment by mayeut** [comment]
This bug is not in the quay.io/pypa/musllinux_1_1_ppc64le image, this is a QEMU bug:
[native ppc64le](https://app.travis-ci.com/github/pypa/manylinux/builds/255160053) run is OK
[QEMU 7.0.0](https://github.com/pypa/manylinux/runs/8169288726?check_suite_focus=true) run is OK
**[QEMU 6.2.0](https://github.com/pypa/manylinux/runs/8169288773?check_suite_focus=true) run is KO**

cc @dvarrazzo

**Comment by dvarrazzo** [comment]
Thank you very much, good finding! :+1:
