### ISSUE TITLE
Allow disabling /host mount

### ISSUE THREAD

**Issue by rcurtin** [pypa/cibuildwheel#1344]
### Description

Hi there.  cibuildwheel has made my life very easy and I really appreciate the time you put into it.  However, there is one detail about it that, it turns out, can make my life (and others' lives) very hard!

The fact that the host filesystem is mounted in the Docker container at `/host` is actually a bit of a hazard, and I'm hopeful that you might consider a way that I can disable this mount.

Here is why it's dangerous.  Consider a pre-build script like this:

```
wget https://mylibrary.net/files/mylibrary-1.0.0.tar.gz
tar -xvzpf mylibrary-1.0.0.tar.gz
cd mylibrary-1.0.0/
mkdir build/
cd build/
cmake ../
make
cd ../../

# Clean up the workspace.
rm -rf *
```

Now there is a big, easy-to-make error here---what happens if the wget fails?  The script blows along happily, fails to `cd` into the source (because it failed to download and unpack), continues along, does `cd ../../` (now it's in `/`!), then blows away the entire filesystem with that `rm -rf *` call.  Since the *host* root is mounted at `/host`, *that* gets blown away too, then you find yourself needing to burn a USB stick to reinstall the OS.

Naturally, the solution for users is to be careful with the scripts they are writing.  But it would be great also if there was an option to disable this behavior---I don't need it, and it violated my (misinformed?) assumption that the container was ephemeral and I could write awful buggy crap.

**Comment by joerick** [comment]
Hm. So I think that you're saying that because there could be arbitrary scripts in the build process, we should have the option of isolating the build process from the build system. 

- First, a little advice on scripting... I'd recommend that in any kind of build script, you use `set -o errexit` at the start - this will exit the script on the first failure. Also, I'd recommend against ever putting `rm -rf *` in a script. If you need to clean up some files after an operation, put them in a subdir/tempdir and remove that (and specifically that) at the end.
- Secondly, we could only ever isolate the host system on linux. On macOS and Windows, the build runs on the host directly as the current user and has permissions to manipulate the host system. So, even if we did disable the `/host` mount, we couldn't change our stance on the trust model/carefulness required to build packages, because of macOS and Windows.
- Thirdly, building Python packages from sdist will always require the execution of arbitrary code (setup.py or build-system.build-backend), even if it's not via a cibuildwheel hook, so I'm not sure we'd want to provide the safety-net of isolation in cibuildwheel, when end-users might end up running the sdist directly on their own machine.

So my opinion is that a few good scripting practices will get you a long way!

**Comment by rcurtin** [comment]
Thanks for the detailed response.  You are certainly right that more reasonable scripting practices would have prevented this---now that I have learned a painful lesson, I have employed those. :)

I did not know the extra context about OS X and Windows; so, I suppose you are right that it doesn't make sense to disable the host mount only on Linux.

It might be nice to be a little clearer in the documentation that the host filesystem is mounted for the Linux images, but, I'm not really able to make a strong case for precisely what to do.  Maybe it's fine as-is.  In any case, probably the more important thing in my opening this issue is just to bring awareness to the possibility---which given your response I have succeeded at.

Anyway, thanks again for the response.  If you don't see any changes that should come out of this, please feel free to close the issue. :+1:
