### ISSUE TITLE
GitHub action hangs after completion (Ubuntu with aarch64)

### ISSUE THREAD

**Issue by Ezibenroc** [pypa/cibuildwheel#1447]
### Description

Hello,

I tried to add support for Linux ARM wheels for my project. I have been using for a while cibuildwheel on this project for other wheels without any issue (Linux, MacOS and Windows).
With `os=ubuntu-20.04` and `cibw_archs=aarch64`, the GitHub action seems to be stuck at the very end, after the "Complete Job" step. The job eventually gets killed after 6h by the timeout.
I saw this issue mentionned [in this comment](https://github.com/pypa/cibuildwheel/issues/1272#issuecomment-1250034254), but it does not seem to be resolved.

Is there any known fix for this problem?

### Build log

https://github.com/Ezibenroc/PyRoaringBitMap/actions/runs/4557868995/jobs/8040071807

### CI config

https://github.com/Ezibenroc/PyRoaringBitMap/blob/744ed0b33d7c68e562b8367f07255a5347116235/.github/workflows/buildwheels.yml

**Comment by joerick** [comment]
> Is there any known fix for this problem?

I don't know of one. Because it seems to happen randomly it's very hard to investigate. From my perspective it feels like it's a less common problem now than, say, a couple years ago, but that's only a sense. 

Restarting the job seems the only option. It rarely fails twice in a row. If you notice a pattern to it I'd be interested to hear.

**Comment by Ezibenroc** [comment]
Indeed, I relaunched the job and the build finished successfully.

**Comment by joerick** [comment]
closing as not an issue with cibuildwheel.
