### ISSUE TITLE
Python 3.12?

### ISSUE THREAD

**Issue by nedbat** [pypa/cibuildwheel#1505]
### Description

Now that CPython 3.12.0b1 is out, I would like to produce wheels for it.  I know the cibuildwheel docs say to wait for rc1, but the advice from Brett Cannon and Thomas Wouters is that it is fine to ship wheels now as long as I produce new wheels in the unlikely event that the ABI changes.

I [tried specifying 3.12, but it failed](https://github.com/nedbat/coveragepy/actions/runs/5073139235/jobs/9111774802#step:6:72)
```
cibuildwheel: No build identifiers selected: BuildSelector(build_config='cp312-*', skip_config='', requires_python=<SpecifierSet('>=3.7')>, prerelease_pythons=True)
```

### Build log

https://github.com/nedbat/coveragepy/actions/runs/5073139235/jobs/9111774802#step:6:72

### CI config

https://github.com/nedbat/coveragepy/blob/nedbat/312-kits/.github/workflows/kit.yml

**Comment by henryiii** [comment]
Apologies, that made less sense out of context than I expected it to. The discussion was about the steering council recommendation clashing with cibuildwheel and manylinux's warning, which state pretty much the opposite.

> I'm gambling that it is likely to be stable, and accepting that if it changes, I will need to make new 3.12 wheels.

You can't upload a new Python 3.12 wheel, you only get to upload it once per release. You can delete the broken wheel and (ideally) make a new release with the updated 3.12 wheel, but many projects don't make releases based on fixing 3.12 wheels. If you know what to do, it's fine to do it, I was just defending the cibuildwheel/manylinux stance of making this available but with a warning and a custom flag, and this issue was a handy place to dump the text in a (more) public place. It absolutely will be available soon, and you absolutely can upload if you know what you are doing.

**Comment by henryiii** [comment]
Just checked, the latest manylinux has `Python 3.12.0b1`!

**Comment by nedbat** [comment]
Great, thanks for clearing that up.
> Just checked, the latest manylinux has `Python 3.12.0b1`!

I guess we need a new release of cibuildwheel for it to work?

**Comment by hugovk** [comment]
> You can't upload a new Python 3.12 wheel, you only get to upload it once per release.

It's possible to upload a new wheel for a release via build numbers.

For example, we did it not once but twice in https://github.com/python-pillow/Pillow/issues/6750

https://pypi.org/project/Pillow/9.4.0/#files has:

* `Pillow-9.4.0-cp311-cp311-macosx_10_10_x86_64.whl`
* `Pillow-9.4.0-1-cp311-cp311-macosx_10_10_x86_64.whl`
* `Pillow-9.4.0-2-cp311-cp311-macosx_10_10_x86_64.whl`

**Comment by henryiii** [comment]
That allows you to only upload one new wheel rather than the full set, right? I think I assumed it was the full set. That would help a lot (as long as you tracked failures and actually rebuilt wheels if there was one - and `wheel tags` would help).

I would like to know how common ABI breakages during betas are.

**Comment by hugovk** [comment]
> That allows you to only upload one new wheel rather than the full set, right?

Yes, you can do it for as many or as few as you need. In this Pillow case, we specifically re-uploaded the x86-64 macOS wheels, as only those were broken.

**Comment by henryiii** [comment]
2.13 is out! https://github.com/pypa/cibuildwheel/releases/tag/v2.13.0
