### ISSUE TITLE
Github action with just @v2 version not found

### ISSUE THREAD

**Issue by rogerbinns** [pypa/cibuildwheel#1587]
### Description

I no longer want to specify the full cibuildwheel version and have to keep updating it, so I tried with only **@v2**

Before  ````uses: pypa/cibuildwheel@v2.15.0````

After: ````uses: pypa/cibuildwheel@v2````

That works for other actions, but attempting an action run gives the error message:

    Unable to resolve action `pypa/cibuildwheel@v2`, unable to find version `v2`

### Build log

https://github.com/rogerbinns/apsw/actions/runs/5965705676

### CI config

https://github.com/rogerbinns/apsw/actions/runs/5965705676/workflow

**Comment by henryiii** [comment]
You can use `v2.15`, which will not need updates as often. `v2` is just somewhat commonly added by actions[^1], but is intentionally not supported, since we add and remove platforms (new CPython versions, PyPy releases, muslinux, etc) in "minor" releases, which might surprisingly break you on releases.

If you don't want a pin, or want to have a custom pin, you can use `run: pipx run cibuildwheel <args>` instead of the action. The main reason for the action is to have the dependabot updates. Internally it just runs `pipx run`.

See https://github.com/pypa/cibuildwheel/pull/1517.

[^1]: GitHub's tool to automate this, used by `actions/*` repos, is actually considered private, I believe.
