### ISSUE TITLE
Builds Python 3.12 wheel even if not requested

### ISSUE THREAD

**Issue by cbrnr** [pypa/cibuildwheel#1605]
### Description

Dependabot just tried to update cibuildwheel to the latest version v2.15.0, and this version is trying to build a wheel for Python 3.12 even though I have not enabled it. Specifically, the build options are:

```
Build options:
  platform: linux
  architectures: x86_64
  build_selector: 
    build_config: *
    skip_config: pp* *musllinux*
    requires_python: >=3.8
    prerelease_pythons: False
```

### Build log

https://github.com/cbrnr/sleepecg/actions/runs/6143089397/job/16665930578?pr=187

### CI config

https://github.com/cbrnr/sleepecg/pull/187/files

**Comment by henryiii** [comment]
3.12 is now in RC, which means it is ABI stable and libraries should start shipping 3.12 wheels. Ideally everyone ships wheels before October. It is our policy to enable 3.x wheels by default as soon as RC 1 is out (realistically, about 1-2 days after it is out), and why we recommend using dependabot, so you don't get caught by surprise with this. :) You can skip 3.12 for now (with `skip=cp312-*`), but I'd recommend getting 3.12 wheels out as soon as possible!

**Comment by henryiii** [comment]
NumPy does ship 3.12 wheels, you just have to opt-into them, because they are currently RC wheels. They are shifting to using meson-python instead of setuptools, so they have been slower this cycle. They are planning on a final release in ~7ish days. For now, use:

```
numpy>=1.26.0b1;python_version>='3.12'
numpy;python_version<'3.12'
```

There always will be some point where wheels will be not always available. The correct time to do this is in the RC phase, so that project developers (like you) can work these out and get wheels ready, so users will be ready when the final release fits. Python.org starts recommending the new version on day 1, so libraries need to be ready.

There _is_ an opt-in period of a month or two - it's during the betas ([CIBW_PRERELEASE_PYTHONS](https://cibuildwheel.readthedocs.io/en/stable/options/#prerelease-pythons)), but it's over now. For library authors, RCs _are_ stable versions (ABI is guaranteed stable!).

**Comment by cbrnr** [comment]
Thanks for explaining! You mentioned and recommended dependabot, can this process be automated somehow? I'm using dependabot only for my GitHub Actions currently, but can I use it to update my `pyproject.toml` (and include RCs)?

**Comment by cbrnr** [comment]
Regarding my specific project, I'm now getting the following error after incorporating the suggested changes:

```
RuntimeError: Cannot install on Python version 3.12.0; only versions >=3.8,<3.12 are supported.
```

See [here](https://github.com/cbrnr/sleepecg/actions/runs/6149132789/job/16684378952?pr=187#step:3:1407) for the entire build log.

**Comment by henryiii** [comment]
That's from Numba. Numba uses the CPython byte code to be able to find out how a function was written given the function object, which is not a public part of Python and very much subject to change a lot every release, causing Numba to be very, very slow in adopting new Python versions. Unfortunately, it's often 4 months or so after the final release before Numba can support a new Python version. This is hopefully going to become easier and faster in the future, but not sure when that will be.

Dependabot is great for pinned versions, it doesn't really support ranges. It's also better at GHA than it is for Python.

**Comment by cbrnr** [comment]
Ah yes, I forgot about Numba! I usually only add support for a new Python version once there are wheels for all dependencies, including optional ones. So I guess I'll explicitly set `python_version < "3.12"` for now. Thank you for your help!
