### ISSUE TITLE
delocate.libsana.DelocationError: Failed to find any binary with the required architecture: 'arm64'

### ISSUE THREAD

**Issue by Parskatt** [pypa/cibuildwheel#1828]
### Description

Going from 2.17 -> 2.18 I'm getting the following:

![image](https://github.com/pypa/cibuildwheel/assets/22053118/45018180-d38a-40d5-b057-49e690a5c739)

It seemingly works fine on 2.17.

Am I doing something wrong? Is this a bug?

### Build log

https://github.com/Parskatt/PoseLib/actions/runs/9086347120/job/24971801224

### CI config

https://github.com/Parskatt/PoseLib/commit/40dbc243193b0fa15c789c7b3fa92790d151c8b1

**Comment by Czaki** [comment]
Since delocate 0.11.0 there is added additional validation steep to check if the library contains any binary file with targeted infrastructure. As cibuildwheel pins delocate, then bump of cibuildwheel brings new delocate version with this check. 

Error message means that the build library does not contain any arm64 file. When I download data from succesfull build and inspect architecture:

```
➜  poselib-2.0.2-cp38-cp38-macosx_11_0_arm64 file poselib.cpython-38-darwin.so
poselib.cpython-38-darwin.so: Mach-O 64-bit bundle x86_64
```

it shows x86_64 architecture instead of the expected arm64. 

So it looks like build process in bugged and you need to fix it to build arm64 wheels.

**Comment by henryiii** [comment]
I’d recommend making macos-13 and macos-14 jobs and that will make Intel and AS wheels without cross-compiling. It’s tricky to get the right deps when cross-compiling.

**Comment by Parskatt** [comment]
Is this specifically for cpython 3.8? I remember seeing something about having to cross compile there. 

Regarding macos-13/14 , as far as I can tell I'm already using those runners.

**Comment by mayeut** [comment]
cibuildwheel defaults to the x86_64 installer for Python 3.8 so this is still a cross-compilation, c.f. https://cibuildwheel.pypa.io/en/stable/faq/#macos-building-cpython-38-wheels-on-arm64

Another workaround (not yet in the docs) for GHA is to add an `actions/setup-python` step e.g.
```yml
- uses: actions/setup-python@v5
  with:
    python-version: '3.8'
```

This uses the universal2 installer of Python 3.8 on macOS arm64 and cibuildwheel will not overwrite an existing installation.
You might want to protect this with an `if: ...` in order not to install it on every platform (even though it should be harmless, it's still a waste of resources when python 3.8 is not pre-installed on the runner).

**Comment by Parskatt** [comment]
Thanks! For now I'll just skip the 3.8 build for apple silicon I think, but that does seem like it would solve things.
I'll close the issue.
