### ISSUE TITLE
Update the versions of PyPy

### ISSUE THREAD

**Issue by mattip** [pypa/cibuildwheel#743]
xref numpy/numpy#19383 where an older version of cibuildwheel (1.7.4) tripped up a user since they were getting a much older PyPy.

**Comment by mattip** [comment]
I think PyPy on windows 64 is also supported now, no?

**Comment by henryiii** [comment]
You need cibuildwheel 2.0 get get windows 64, which is not fully out yet (a bug in pip is in the way for build support, #740, and a few other things). But the everything that was supported before should still be stable, so using 2.0.0a4 should be safe unless you are activating the experimental `pypa/build` support.

cibuildwheel pins everything by default. So they need to update the cibuildwheel pin.

The readme should be correct - the docs are for cibuildlwheel 1.x until the new release, unless you go to the `latest` version.  Default is `stable`.

**Comment by mattip** [comment]
Supporting PyPy 7.3.3 as the last version is problematic, as pointed out in the issue above. That version of PyPy does not play well with some versions of NumPy. Does changing a PyPy version require a new version of cibuildwheel?

**Comment by henryiii** [comment]
We could backport the update to the 1.x branch, I suppose. One of the biggest issues is that pypy3.6 was dropped in the latest version, so this would be a bit of a bigger change than we wanted to deal with - would need to be 1.12 (also of course the change to Windows 64). Also, we currently are using the manylinux* wheels, which are 3.7+ only (no 2). Also, since we'd already dropped Python 2, the backport might not initially handle pypy2 correctly.

I might be willing to give it a shot later if it seems like a good idea.

**Comment by mattip** [comment]
Ahh, I see. So more trouble than it is worth it seems. Thanks for the explanation.
