### ISSUE TITLE
Update available pypy version in docker to v7.3.5

### ISSUE THREAD

**Issue by mattip** [pypa/cibuildwheel#757]
Over at matplotlib they are [running into issues](https://github.com/matplotlib/matplotlib/issues/20637) using `pp37-*` because it is using pypy3.7-v7.3.3 from the pypywheels/manylinux2010-pypy_x86_64:2020-12-11-f1e0e80 docker image. What is the process to update that to contain pypy3.7-v7.3.5?

**Comment by mattip** [comment]
Ahh, I see one master it is https://github.com/pypa/cibuildwheel/blob/5e6ffa9f2529cbc011edfd631dd398ca5c4bc3a2/cibuildwheel/resources/pinned_docker_images.cfg#L13-L16

So this is waiting on a new release of cibuildwheel? Is this also connected to #711?

**Comment by henryiii** [comment]
I'd say it's more connected to #743. 7.3.5 removed PyPy 3.6, so we made the update uniformly in master (as part of 2.0).

2.0 is planned for release by Friday, so if waiting is fine, then that's when it should drop. If not, there's nothing (known) wrong with `2.0.0b2`, several packages are already using that in production. If that's still not enough, then we probably could backport the image update, though it would need to be to the old pypywheels/manylinux wheels, since those should still have an older pypy 3.6 as well as pypy2 in them. Backporting the entire patch (including macOS and Windows) would require removing pypy3.6, so that could be a 1.13, I guess?

Finally, the simplest fix till Friday might be for MPL to just pin a newer image for now. Those pins are easy to set for PyPy only (see #711). They should be able to do a newer pypywheels easily, and possibly a pypa/manylinux as long as they don't try to build pypy36.

**Comment by mattip** [comment]
> 2.0 is planned for release by Friday, so if waiting is fine

Yup, fantastic. Good luck with the release
