### ISSUE TITLE
Consider auto-correcting underscores to dashes in TOML options

### ISSUE THREAD

**Issue by joerick** [pypa/cibuildwheel#761]
From https://github.com/pypa/cibuildwheel/pull/759#discussion_r670922746

While TOML prefers dashes, as a Python programmer, it's easy to accidentally write underscores for option names. 

I wonder if it would be nice to do autofix this a la `option_name.replace("_","-")`, after we read these. pip does something similar - if you do e.g. `pip install python_dateutil`, it will still find `python-dateutil`, because underscores are invalid.

**Comment by henryiii** [comment]
I'm not really a fan of this - I'd rather force "one correct" way to do it, rather than making it arbitrary. You'll immediately get an error if you put something in incorrectly, so I think it's fairly low friction. And then what do you do if `a_b` and `a-b` are both present? Normally the TOML parser should handle the errors if you duplicate a key, but this is not a TOML error, so we'd have to handle it.

**Comment by joerick** [comment]
Hmm. yes. Perhaps just a nicer error message, like `Unknown option "before_all". Perhaps you meant "before-all"?`

**Comment by henryiii** [comment]
I really like it when Python 3.10 does this, and it's pretty easy to implement with `difflib.get_close_matches`, so I like this idea. Also would help for near misspellings.
