### ISSUE TITLE
When CIBW_PROJECT_REQUIRES_PYTHON exists, you don't need to check if "setup.py" exists

### ISSUE THREAD

**Issue by snnn** [pypa/cibuildwheel#794]
Please see the code below:
```python
    package_files = {"setup.py", "setup.cfg", "pyproject.toml"}

    if not any(package_dir.joinpath(name).exists() for name in package_files):
        names = ", ".join(sorted(package_files, reverse=True))
        msg = f"cibuildwheel: Could not find any of {{{names}}} at root of package"
        print(msg, file=sys.stderr)
        sys.exit(2)

    # This is not supported in tool.cibuildwheel, as it comes from a standard location.
    # Passing this in as an environment variable will override pyproject.toml, setup.cfg, or setup.py
    requires_python_str: Optional[str] = os.environ.get(
        "CIBW_PROJECT_REQUIRES_PYTHON"
    ) or get_requires_python_str(package_dir)
```

When CIBW_PROJECT_REQUIRES_PYTHON environment variable exists, I think we can skip the check of " if not any(package_dir.joinpath(name).exists() for name in package_files)".  Some packages do out of source tree build. They may prefer to run setup.py in their build directory, which could be `package_dir`.  But they may copy(or generate) setup.py to `package_dir` during `CIBW_BEFORE_BUILD`

BTW, I would like to know your suggestion for a very common problem: A package with native code depends on numpy. If the package was built with numpy version X, then at runtime it will require numpy version >= X.  So the "pyproject.toml" may be generated at build time depending on the build environment. For example, it may require numpy version>=1.16 for python version 3.6-3.9 but numpy version>=1.21 for python version >=3.10 because numpy 1.16 doesn't support python 3.10(it was release much before that).  So, how to incorporate such things into cibuildwheel?

**Comment by henryiii** [comment]
The check has nothing to do with `CIBW_PROJECT_REQUIRES_PYTHON` - it's a check for a valid Python package. If you check the history, you'll see it predates the lines about the project requires by quite a bit. And the project requires part will not look in setup.py or any other file if that variable is set. If none of those files exist, `pip wheel .` or `python -m build --wheel` will fail - they have similar checks. You can't build a package if none of those files exist. Actually, only `setup.py` and `pyproject.toml` are needed here - both `build` and `pip` do not allow a package that does not have at least one of those.

If your `setup.py` is generated, then include a `pyproject.toml` (you should anyway), or make sure it's generated first (or just empty if it's going to be replaced?).

---

The most common case where this comes up ironically is NumPy; and you do with environment markers, just like you'd do with normal requirements. For your example,

```toml
[build-system]
requires = [
    "numpy==1.16; python_version<'3.10'",
    "numpy==1.21; python_version>='3.10'",
...
```

The reason is is common is that your wheels should always be compiled with the oldest version of NumPy you support - when you combine this with the fact there's an "oldest supposed numpy" for each python version and special achetectures, this becomes quite a matrix of values. See SciPy's [oldest-supported-numpy](https://pypi.org/project/oldest-supported-numpy) (mentioned in our docs) for a package that literally just does this for you.

There's not really any harm in compiling against an older version than you support at runtime, by the way - it's very unlikly you'll use a new API in the C code that's not available in 1.13 (there really aren't many/any), but you can mix `oldest-supported-numpy` with a raw `numpy` requirement based on Python version too if you want.

PS: If you use pybind11, you don't need to compile with NumPy present at all, so this is all not needed.

**Comment by henryiii** [comment]
Here's an example of a "mix" from a Cython package that still supports Python 2.7 (mostly because it's deprecated): https://github.com/scikit-hep/probfit/blob/50d45633e90af7ba564d9026b24914b042d1e0cd/pyproject.toml#L6-L7

**Comment by snnn** [comment]
Thank you for the detailed explanation. Adding a `pyproject.toml` to `package_dir` would be the easiest for me. 

To give you more background, before moving to cibuildwheel, I build our package in a way like:
```bash
git clone https://github.com/mypackage/mypackage
cd mypackage
mkdir build
cmake ..
make
python ../setup.py bdist_wheel  #packaging the files
```
Compare to the other packages, It is a bit wired.  It makes me harder to use cibuildwheel. 

Then per your suggestion, I found I can do this:
1. Check in a folder named 'build' with an empty `pyproject.toml` file in it.
2. In our build pipeline, set the envs like:
```
        CIBW_ARCHS: x86_64
        CIBW_PROJECT_REQUIRES_PYTHON: ">=3.6, <3.10"
        CIBW_BEFORE_BUILD: rm -rf build && run_build_script.sh && cp setup.py Release 
```

Then it works.  Later on I can fill pyproject.toml with more useful data.  But it will only be used for the `cibuildwheel` tool only.  It won't be part of the build.  For the build,  I would prefer to generate it on the fly based on CPU arch, the packages in the docker , etc.   The `oldest-supported-numpy` solution doesn't work me. numpy is too popular.  I got my docker base image from somewhere else(like Nvidia/AMD/Facebook), they already added a lot of software there and sometimes it may contain a python package that has a specific numpy version requirement, which is much newer than the one specified in  `oldest-supported-numpy`.  I can't remove the package, so I can't downgrade numpy and I can't determine which numpy version to us.  If today I say my package requires `numpy>=1.16`, tomorrow the build env could get changed without my notice. You know, I don't want to frequently update my source code because of such things. I would rather than getting the numpy version during the build then put it into setup.py(or setup.cfg/pyproject.toml).
