### ISSUE TITLE
Numba ahead of time compiled extensions

### ISSUE THREAD

**Issue by Korijn** [pypa/cibuildwheel#798]
I'm trying to package a numba extension by using ahead of time compilation so that the numba dependency is only build-time and not runtime.

See here: https://numba.readthedocs.io/en/stable/user/pycc.html

As you can see, they expect you to import the source module in setup.py, but of course, that falls on its face because that is not available when running `pip wheel`.

I'm wondering if there is some magical syntax that I could use in `pyproject.toml` to make the source module available during the build? Or any other tricks?

**Comment by Czaki** [comment]
adding numba to `requires` in `build-system`?

https://github.com/4DNucleome/PartSeg/blob/d5e800d400dc78c9133304290be28d5a04637c17/pyproject.toml#L3

**Comment by Korijn** [comment]
Yeah, I did that, but as you can see in the example, they require you to import not just numba, but your own source code that needs to be compiled:

```python
from distutils.core import setup

from source_module import cc  # <--- this import

setup(...,
      ext_modules=[cc.distutils_extension()])
```

That's the import that fails.

**Comment by henryiii** [comment]
That should be solved by using normal means, though? Probably by adding `source_module`'s containing folder to the path or something similarly distasteful? Yes, that means you have to have all requirements required for import at build-time and not through normal packaging - so anything else you _require_ has to be listed in `requires` too, but you actually do need that since the package has to be imported to be able to run with numba to AoT compile.

**Comment by Korijn** [comment]
> adding source_module's containing folder to the sys.path in setup.py or something similarly distasteful

That's precisely what I'm resorting to now but it feels wrong...

**Comment by henryiii** [comment]
I think it's required, because the package has not yet been built yet, but you need to be able to import Python code to run numba to ahead-of-time compile it to build the package. Doesn't make it feel good, but that's why it's required. Pyproject.toml protects you here and lets you ensure what you need is available at build time.

**Comment by Korijn** [comment]
OK, if that's just the way it is, we're done here :) thanks for the help
