### ISSUE TITLE
Make i686 wheels an opt-in

### ISSUE THREAD

**Issue by abitrolly** [pypa/cibuildwheel#874]
### Description

Debian stats https://popcon.debian.org/ show that between there are not many users nowadays who use i386/i686 platforms.

amd64: 190535
i386: 14151

Or only 7%, from which not everybody is a Python developer who installs wheels with `pip`.

```
In [1]: amd64=190535 
   ...: i386=14151                                                                   

In [3]: str(100*i386/(amd64+i386))+'%'                                               
Out[3]: '6.9135163127913%'
```

This will cut carbon footprint a bit (and release a bit of CI quota).

**Comment by joerick** [comment]
As @henryiii says, opt-in doesn't really fit with how cibuildwheel works currently. 

> This will cut carbon footprint a bit (and release a bit of CI quota).

This is an interesting point, but building a wheel seems to me that it would save energy overall, because installers of the package don't have to spin cycles compiling it themselves. I wouldn't be confident calling it either way!
