### ISSUE TITLE
Is it too soon to ask for 3.11 support?

### ISSUE THREAD

**Issue by hauntsaninja** [pypa/cibuildwheel#946]
### Description

Currently, running on 3.11 gives you `cibuildwheel: No build identifiers selected: BuildSelector(build_config='cp311-*', skip_config='*-manylinux_i686 *-win32')` and exit code 3.

It looks like at a minimum something needs to be added here: https://github.com/pypa/cibuildwheel/blob/main/cibuildwheel/resources/build-platforms.toml

### Build log

https://github.com/python/typed_ast/runs/4398265737?check_suite_focus=true

**Comment by henryiii** [comment]
Python 3.11 will need to be added to manylinux before we can support it. It generally gets added at beta 1, IIRC. Then we will enable it too, but behind the prerelease flag (since the ABI is not stable at that point, so wheels should not be uploaded). Then around RC 1, we'll bring it out from behind the prerelease flag since ABI is promised to be stable at that point.
