### ISSUE TITLE
Specifying constraints for build-system dependencies on Linux

### ISSUE THREAD

**Issue by hodgestar** [pypa/cibuildwheel#955]
### Description

I'm building a project with numpy and Cython code. The project supports many versions of numpy, so the `pyproject.toml` `build-system.requires` is just:
```
[build-system]
requires = [
    ...
    "cython>=0.29.20",
    "numpy>=1.16.6",
]
```
However, when build wheels for PyPI, the project should be build with the oldest numpy that supports the relevant Python and architecture so that the compiled Cython code will run on any supported numpy version.

Currently there seems to be no way to achieve this because pip's isolated builds re-install the latest numpy even if one is already installed and `CIBW_DEPENDENCY_VERSIONS` isn't applied to the `pip wheel` command on Linux (although it is applied to the test dependencies).

Could the constraints be passed to `pip wheel` or is there another way to achieve this? Would using the newer `build` based wheel creation be better?

P.S. I could hardcode the constraints into the `pyproject.toml` file, but that would prevent anyone else from building against their own preferred version of numpy, which they may want to do for a large number of reasons (e.g. testing, performance, bugs in older numpy, using the numpy they already have, etc).

P.P.S. It looks like using `build` will not help because the build package rejected a request to support constrains and currently cibuildwheel also uses build isolation when using `build`.

**Comment by henryiii** [comment]
You should replace numpy with oldest-supported-numpy in your pyproject.toml. See https://github.com/scipy/oldest-supported-numpy and/or https://cibuildwheel.readthedocs.io/en/stable/options/#examples_9.

**Comment by henryiii** [comment]
If for some reason users want to use a newer NumPy, they can disable build isolation - that's why that's there and is one of the main things it's for (conda for example uses a specific numpy version; but it also must disable build isolation, since it can't use any pip packages in the build). If they are using build-isolation, they should get exactly the same build every time, which is why `oldest-supported-numpy` exists.

**Comment by hodgestar** [comment]
> You should replace `numpy` with `oldest-supported-numpy` in your pyproject.toml. See https://github.com/scipy/oldest-supported-numpy and/or https://cibuildwheel.readthedocs.io/en/stable/options/#examples_9.

Thank you for the suggestion, but `oldest-supported-numpy` is not correct even for the PyPI builds in this case since the project has it's own minimum numpy version (1.16.6).

**Comment by hodgestar** [comment]
> If for some reason users want to use a newer NumPy, they can disable build isolation - that's why that's there and is one of the main things it's for (conda for example uses a specific numpy version; but it also must disable build isolation, since it can't use any pip packages in the build). If they are using build-isolation, they should get exactly the same build every time, which is why `oldest-supported-numpy` exists.

Turning off build isolation doesn't solve the problem either because if the build dependencies are checked, they will fail (e.g. this happens with `build`) and in any case the dependencies will be factually incorrect (i.e. that specific version of numpy is not required to build the project, it is only required to build the project in certain situations).

**Comment by hodgestar** [comment]
The PR where I am trying to hack my way around this issue -- https://github.com/qutip/qutip/pull/1735 :)

**Comment by henryiii** [comment]
When you are *building*, having a lower version is generally considered safe (the reasoning is in oldest-supported-numpy). Even the PyData libraries (which have an even higher minimum numpy) are using it. However, _if_ it is a real problem for you because you use something only available in 1.16 _at build time_ (verify it is first!), you can select manually for just the cases were you need the higher version. But it's extremely unlikely you actually care.

If you build, ***you should get the same result regardless of whether and what version of X happens to be installed in your environment** - this is the point of build isolation. Your code above is guaranteed to be broken, actually. If I run `pip install project numpy==1.20`, your code above (I'm calling `project`) would download `numpy>=1.16`, which is NumPy 1.21.4 at the moment, and then at runtime `project` would  have `numpy==1.20` and `project` which would have been built with numpy 1.21, and so would not load.

These tools were literally built for this purpose. Please use them instead of trying to invent a new solution. The NumPy developers maintain `oldest-supported-numpy` specifically for isolated builds.

**Comment by henryiii** [comment]
For build, the dependency check is a little irritating, but you should use `-nx` instead of `-n`.

**Comment by hodgestar** [comment]
Thanks for the help. I am closing this for now.
