### ISSUE TITLE
If `CIBW_ARCHS: auto64` is set, cibuildwheel still tries to start a Docker container for i686 wheels, but fails doing so

### ISSUE THREAD

**Issue by lpsinger** [pypa/cibuildwheel#992]
### Description

We are trying to skip 32-bit wheels. We tried setting `CIBW_ARCHS: auto64`. This doesn't skip the i686 builds, but it does cause them to fail!

### Build log

https://github.com/healpy/healpy/pull/742/checks

### CI config

https://github.com/healpy/healpy/blob/5869a2927a724af43f07141c21324d24b8a5d205/.github/workflows/cibuildwheel.yml

**Comment by henryiii** [comment]
That is not running 32-bit builds. That's running musllinux, which is failing, because you have `yum` commands, and musllinux uses `apk`. You can use an `[[tool.cibuildwheel.overrides]]` section in your pyproject.toml file (you should to use that instead of environment variables) to change your command on musllinux, or you can add musllinux to your skip.
